name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - "src/script/**"
      - ".github/workflows/docker.yml"
  pull_request:
    branches:
      # Only trigger for PRs against `main` branch.
      - main
    paths:
      - "src/script/**"
      - ".github/workflows/docker.yml"

jobs:
  dockerize:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: 'dependabot-azure-devops'
      DOCKER_BUILDKIT: 1 # Enable Docker BuildKit

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Pull Docker base image & warm Docker cache
      run: docker pull "angelwang1234567/$IMAGE_NAME:latest"

    - name: Build image
      run: |
        docker build \
        -f src/script/Dockerfile \
        -t "angelwang1234567/$IMAGE_NAME:latest" \
        -t "angelwang1234567/$IMAGE_NAME:$GITVERSION_FULLSEMVER" \
        -t "angelwang1234567/$IMAGE_NAME:$GITVERSION_MAJOR.$GITVERSION_MINOR" \
        -t "angelwang1234567/$IMAGE_NAME:$GITVERSION_MAJOR" \
        --cache-from angelwang1234567/$IMAGE_NAME:latest \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        src/script

    - name: Log into registry (Docker Hub)
      if: ${{ (github.ref == 'refs/heads/main') || (!startsWith(github.ref, 'refs/pull')) || startsWith(github.ref, 'refs/tags') }}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to Docker Hub (latest)
      if: github.ref == 'refs/heads/main'
      run: |
        docker push "angelwang1234567/$IMAGE_NAME:latest"

    - name: Push image to Docker Hub (FullSemVer)
      if: "!startsWith(github.ref, 'refs/pull')"
      run: |
        docker push "angelwang1234567/$IMAGE_NAME:$GITVERSION_FULLSEMVER"

    - name: Push image to Docker Hub (major, minor)
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker push "angelwang1234567/$IMAGE_NAME:$GITVERSION_MAJOR.$GITVERSION_MINOR"
        docker push "angelwang1234567/$IMAGE_NAME:$GITVERSION_MAJOR"
